# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('backweb', '0002_auto_20180825_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'tt_cart',
            },
        ),
        migrations.CreateModel(
            name='OrderGoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Order')),
            ],
            options={
                'db_table': 'tt_order_goods',
            },
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='typename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
