# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_cart_c_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserReceivInfo'),
        ),
    ]
