# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0006_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_prices',
            field=models.FloatField(default=0),
        ),
    ]
