# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0007_order_o_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoodsmodel',
            name='goods_price',
            field=models.FloatField(default=0),
        ),
    ]
