# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180827_1737'),
        ('backweb', '0008_ordergoodsmodel_goods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse', models.DateTimeField(auto_now=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'tt_userbrowse',
            },
        ),
    ]
