# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0009_userbrowse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbrowse',
            old_name='browse',
            new_name='browse_time',
        ),
    ]
