# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0010_auto_20180827_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrowse',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Goods'),
        ),
    ]
