# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30, unique=True)),
                ('u_password', models.CharField(max_length=200)),
                ('u_email', models.CharField(max_length=20, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('is_superuser', models.BooleanField(default=0)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'tt_user',
            },
        ),
        migrations.CreateModel(
            name='UserReceivInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('relation_address', models.CharField(max_length=200)),
                ('detail_address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'tt_userinfo',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255)),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
    ]
