# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useraddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userphone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userreceivinfo',
            name='is_default',
            field=models.BooleanField(default=0),
        ),
    ]
